apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cs-operator
  template:
    metadata:
      labels:
        name: cs-operator
    spec:
      serviceAccountName: cs-operator
      containers:
        - name: cs-operator
          image: REPLACE_IMAGE
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cs-operator"
            - name: IN_CLUSTER
              value: "true"
